---
- name: Basic server setup
  hosts: local
  become: true

  tasks:
     - name: Ensure curl is installed
       apt: 
          name: curl
          state: present

     - name: Ensure git is installed
       apt:
          name: git
          state: present
